### ISSUE TITLE
Install cdr-tools for coreldraw 2017 (X9)

### ISSUE THREAD

**Issue by abstractindia** [cdrpro-macros/cdr-tools#1]
I want to install cdr-tools in coreldraw 2017 (x9). How can I do it?

**Comment by SanichKotikov** [comment]
@abstractindia hi. You can download & copy `CdrTools.gms` from this repository into the user's GMS folder (exact location you can find in the Internet). If it doesn't work, you might need some VBA skills to fix some issues.

**Comment by abstractindia** [comment]
As per the instructions, I copied the CdrTools.gms to the required folder (C:\Users\abstr\AppData\Roaming\Corel\CorelDRAW Graphics Suite 2017\Draw\GMS). I launched CorelDRAW and run  the macro CdrToolsEx -> Install. It prompted me to locate the dll file, I browsed and selected the CdrToolsEx.dll. It got installed but when I run the docker, I get blank docker like in the attached screen shot. Please guide me now what to do.
![2018-03-25001](https://user-images.githubusercontent.com/14857472/37887971-65f4522e-30e2-11e8-9ec0-e0225ca2adec.jpg)

**Comment by SanichKotikov** [comment]
`CdrToolsEx` is a different tool and have been never updated for X8 or 2017. This repository is about CdrTools vba macros, and not about CdrToolsEx C# addon.
